import cv2
import pytesseract
from flask import Flask, render_template, Response
from utils import ocr_core

app = Flask(__name__)

# Initialize webcam
cap = cv2.VideoCapture("/dev/video1")

def generate_frames():
    while True:
        # Capture frame from webcam
        success, frame = cap.read()
        
        if not success:
            break
        
        # Perform OCR on the frame and get bounding boxes
        frame_with_text = ocr_core(frame)

        # Encode the frame in JPEG format
        ret, buffer = cv2.imencode('.jpg', frame_with_text)
        frame = buffer.tobytes()
        
        # Yield the frame as part of an HTTP response
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/video_feed')
def video_feed():
    # Return the response generated by the `generate_frames` function
    return Response(generate_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')

if __name__ == "__main__":
    app.run(debug=True)
